name: Learn basic of GitHub Action

on:
  push:
    branches:
      - main

jobs:
  helloworld:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest


    steps:
      - name: print hello
        run: echo "hello world !!"

      - name: print chalo
        run: echo "chalo world !!" 

  chaloworld:
    runs-on: ubuntu-latest

    steps:
      - name: print hello
        run: echo "hello world !!"

      - name: print chalo
        run: echo "chalo world !!"

        

        
